### ISSUE TITLE
Wrap command actions in try-catch blocks to avoid mitmproxy crashes

### ISSUE THREAD

**Issue by pstens** [Dima-369/mitmproxy-config#1]
When the request/response body is not valid JSON, the add-on script throws an exception. Hence, the whole `mitmproxy` process crashes with the following stack trace.
This is kinda frustrating whenever there's a huge history of calls that gets wiped away.

```
❯ mi
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/window.py", line 310, in keypress
    k = super().keypress(size, k)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/urwid/container.py", line 1123, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 201, in keypress
    return self.ab.keypress(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 149, in keypress
    self.prompt_execute(text)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 169, in prompt_execute
    msg = p(txt)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/statusbar.py", line 115, in execute_command
    execute(txt)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/tools/console/commandexecutor.py", line 18, in __call__
    ret = self.master.commands.execute(cmd)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/command.py", line 266, in execute
    return self.call_strings(command_name, args)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/command.py", line 252, in call_strings
    return self.commands[command_name].call(args)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/command.py", line 122, in call
    ret = self.func(*bound_args.args, **bound_args.kwargs)
  File "/usr/local/Cellar/mitmproxy/6.0.2_1/libexec/lib/python3.9/site-packages/mitmproxy/command.py", line 296, in wrapper
    return function(*args, **kwargs)
  File "/Users/patrickstens/.mitmproxy/addon-commands.py", line 73, in do
    format_json_human()
  File "/Users/patrickstens/.mitmproxy/addon-commands.py", line 16, in format_json_human
    pyperclip.copy(json.dumps(json.loads(raw), indent=2))
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy
```

**Comment by pstens** [comment]
I'll prepare a PR
